// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from '@/app/page.info';
import * as LoginRoute from '@/app/(auth)/login/page.info';
import * as LogoutRoute from '@/app/logout/page.info';
import * as RegistrationRoute from '@/app/(auth)/registration/page.info';
import * as ResetPasswordRoute from '@/app/(auth)/reset-password/page.info';
import * as MyProfileRoute from '@/app/my/profile/page.info';

export const Home = makeRoute('/', {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Login = makeRoute('/(auth)/login', {
  ...defaultInfo,
  ...LoginRoute.Route,
});
export const Logout = makeRoute('/(auth)/logout', {
  ...defaultInfo,
  ...LogoutRoute.Route,
});
export const Registration = makeRoute('/(auth)/registration', {
  ...defaultInfo,
  ...RegistrationRoute.Route,
});
export const ResetPassword = makeRoute('/(auth)/reset-password', {
  ...defaultInfo,
  ...ResetPasswordRoute.Route,
});
export const MyProfile = makeRoute('/my/profile', {
  ...defaultInfo,
  ...MyProfileRoute.Route,
});
