// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from '@/app/page.info';
import * as LoginRoute from '@/app/login/page.info';

export const Home = makeRoute('/', {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Login = makeRoute('/login', {
  ...defaultInfo,
  ...LoginRoute.Route,
});
