// Automatically generated by declarative-routing, do NOT edit
import { z } from 'zod';
import { makeGetRoute, makeRoute } from './makeRoute';

const defaultInfo = {
  search: z.object({}),
};

import * as HomeRoute from '@/app/page.info';
import * as LoginRoute from '@/app/login/page.info';
import * as LogoutRoute from '@/app/logout/route.info';

export const Home = makeRoute('/', {
  ...defaultInfo,
  ...HomeRoute.Route,
});
export const Login = makeRoute('/login', {
  ...defaultInfo,
  ...LoginRoute.Route,
});

export const getLogout = makeGetRoute(
  '/logout',
  {
    ...defaultInfo,
    ...LogoutRoute.Route,
  },
  LogoutRoute.GET,
);
